# SPDX-FileCopyrightText: 2021 Tezos Commons
# SPDX-License-Identifier: LicenseRef-MIT-TC

name:                baseDAO-ligo-meta
version:             0.4.0.0
license:             MIT
license-file:        LICENSE
author:              Serokell, Tocqueville Group
git:                 git@github.com:tezos-commons/baseDAO.git
copyright:           2020-2021 TQ Tezos, 2021-2022 Tezos Commons

extra-doc-files:
- README.md
extra-source-files:
- resources/lambdaDAO.tz
- resources/lambdaDAO_storage.tz
- resources/lambdaregistryDAO.tz
- resources/lambdaregistryDAO_storage.tz
- resources/lambdatreasuryDAO.tz
- resources/lambdatreasuryDAO_storage.tz
- resources/registryDAO.tz
- resources/treasuryDAO.tz
- resources/trivialDAO.tz
- resources/trivialDAO_storage.tz
- resources/registryDAO_storage.tz
- resources/treasuryDAO_storage.tz
- resources/plist_contract.tz

description:         Tools and tests for the LIGO baseDAO contract.

verbatim:
  cabal-version: 2.2

default-extensions:
  - AllowAmbiguousTypes
  - BangPatterns
  - BlockArguments
  - ConstraintKinds
  - DataKinds
  - DefaultSignatures
  - DeriveAnyClass
  - DeriveDataTypeable
  - DeriveFoldable
  - DeriveFunctor
  - DeriveGeneric
  - DeriveTraversable
  - DerivingStrategies
  - DerivingVia
  - EmptyCase
  - ExistentialQuantification
  - FlexibleContexts
  - FlexibleInstances
  - GADTs
  - GeneralizedNewtypeDeriving
  - ImportQualifiedPost
  - LambdaCase
  - MultiParamTypeClasses
  - MultiWayIf
  - NamedFieldPuns
  - NegativeLiterals
  - NoImplicitPrelude
  - NumDecimals
  - OverloadedLabels
  - OverloadedStrings
  - PatternSynonyms
  - PolyKinds
  - QuasiQuotes
  - RankNTypes
  - RecordWildCards
  - RecursiveDo
  - ScopedTypeVariables
  - StandaloneDeriving
  - StrictData
  - TemplateHaskell
  - TupleSections
  - TypeApplications
  - TypeFamilies
  - TypeOperators
  - UndecidableInstances
  - UndecidableSuperClasses
  - ViewPatterns

ghc-options:
  -Weverything
  -Wno-missing-exported-signatures
  -Wno-missing-import-lists
  -Wno-missed-specialisations
  -Wno-all-missed-specialisations
  -Wno-unsafe
  -Wno-safe
  -Wno-missing-local-signatures
  -Wno-monomorphism-restriction
  -Wno-implicit-prelude
  -Wno-unused-packages
  -Wno-prepositive-qualified-module
  -Wno-missing-safe-haskell-mode

dependencies:
  - name: base-noprelude
    version: ">= 4.7 && < 5"

library:
  source-dirs: src
  default-extensions: [ RebindableSyntax ]
  ghc-options: [ -Wno-unused-do-bind ]

  generated-other-modules:
    - Paths_baseDAO_ligo_meta
  dependencies:
    - aeson
    - containers
    - cleveland
    - file-embed
    - filepath
    - text
    - fmt
    - lorentz
    - morley
    - morley-ledgers
    - morley-metadata
    - morley-prelude
    - named
    - template-haskell
    - universum
    - with-utf8

executables:
  baseDAO-ligo-meta:
    main:                Main.hs
    source-dirs:         app
    dependencies:
    - aeson-pretty
    - baseDAO-ligo-meta
    - morley
    - morley-prelude
    - optparse-applicative
    - universum

tests:
  baseDAO-test:
    main:        Main.hs
    source-dirs: test
    build-tools: tasty-discover:tasty-discover

    ghc-options:
    - -threaded
    - -eventlog
    - '"-with-rtsopts=-N -A64m -AL256m"'

    dependencies:
    - HUnit
    - baseDAO-ligo-meta
    - bytestring
    - cleveland
    - aeson
    - containers
    - cryptonite
    - fmt
    - hedgehog
    - lorentz
    - morley
    - morley-ledgers
    - morley-prelude
    - morley-metadata
    - morley-metadata-test
    - mtl
    - named
    - tasty
    - tasty-hedgehog
    - tasty-hunit-compat
    - universum
    - aeson
    - morley-metadata-test
    - morley-metadata
