# SPDX-FileCopyrightText: 2021 Tezos Commons
# SPDX-License-Identifier: LicenseRef-MIT-TC

- message:
  - name: Redundant build-depends entry
  - depends:
    - base-noprelude
    - morley-prelude

- message:
  - name: Weeds exported
  - module:
    - name: Tree
    - identifier:
      - ingredients
      - main

- message:
  - name: Weeds exported
  - module:
    - name: Test.Ligo.Common
    - identifier:
      - getContract
      - getInitialStorage
      - toMetadata
