# SPDX-FileCopyrightText: 2021 Tezos Commons
# SPDX-License-Identifier: LicenseRef-MIT-TC

# To update hackage and stackage indexes used by CI run:
# $ niv update hackage.nix; niv update stackage.nix
resolver: lts-18.10

packages:
  - haskell

extra-deps:

# Stable versions available on Hackage
- cleveland-0.1.1
- morley-client-0.1.1
- morley-prelude-0.5.1
- lorentz-0.13.3

- git: https://gitlab.com/morley-framework/morley.git
  commit: a7fad974928a1854379dee2cd1595e47115e8d91 # master
  subdirs:
    - code/morley

- git: https://gitlab.com/morley-framework/indigo.git
  commit: 8074d3c6a03d6e79b7ddb48b323bca72bf6c2767 # master
  subdirs:
    - .
- git: https://gitlab.com/morley-framework/morley-ledgers.git
  commit: 81ce02e733b6c33e4d4fe8034e65d95f03a5f0a7 # master
  subdirs:
    - code/morley-ledgers
- git: https://gitlab.com/morley-framework/morley-metadata.git
  commit: c7d545897bad10bc98ceb1d9672f184b108dd40e # master
  subdirs:
    - code/morley-metadata

# Required by morley
- git: https://github.com/serokell/base-noprelude.git
  commit: 1282e0b992b00089d55228a2aa9edc4a3581c319
- hex-text-0.1.0.4
- show-type-0.1.1
- named-0.3.0.1
- co-log-0.4.0.1
- colourista-0.1.0.1
- ansi-terminal-0.10.3
- galois-field-1.0.2
- elliptic-curve-0.3.0
- pairing-1.1.0
- protolude-0.2.4
- poly-0.4.0.0
- groups-0.4.1.0
- crypto-sodium-0.0.5.0
- NaCl-0.0.5.0
- libsodium-1.0.18.2
- OddWord-1.0.2.0

# Required by indigo
- summoner-2.0.1.1
- generic-data-0.8.3.0
- neat-interpolation-0.3.2.6
- optparse-applicative-0.15.1.0
- megaparsec-8.0.0
