# SPDX-FileCopyrightText: 2021 Tezos Commons
# SPDX-License-Identifier: LicenseRef-MIT-TC

# To update hackage and stackage indexes used by CI run:
# $ niv update hackage.nix; niv update stackage.nix
resolver: lts-19.3

packages:
  - haskell

extra-deps:
- morley-prelude-0.5.3
- morley-1.19.2
- lorentz-0.15.2
- morley-client-0.3.2
- cleveland-0.3.2

- git: https://gitlab.com/morley-framework/indigo.git
  commit: 78058441a44682706469aebd56f07c93c51ecef1 # master

- git: https://gitlab.com/morley-framework/morley-ledgers.git
  commit: 4c60e54f2739ec8065b2f96ab6f08360b6c85aa0 # master
  subdirs:
    - code/morley-ledgers
- git: https://gitlab.com/morley-framework/morley-metadata.git
  commit: b9daee2e495d3b8f65d0c87f24243e2e95d4a6f9 # master
  subdirs:
    - code/morley-metadata
    - code/morley-metadata-test

# Required by morley
- git: https://github.com/serokell/base-noprelude.git
  commit: c8b06c4c8a271fce0c2f41ab18e88d58e64bac52 # 4.15.1.0
- OddWord-1.0.2.0
- bitvec-1.0.3.0@sha256:f69ed0e463045cb497a7cf1bc808a2e84ea0ce286cf9507983bb6ed8b4bd3993,3977
- colourista-0.1.0.1@sha256:98353ee0e2f5d97d2148513f084c1cd37dfda03e48aa9dd7a017c9d9c0ba710e,3307
- named-0.3.0.1@sha256:418543272f0c844a77639b05276ee3906d5f305cd4cab46fafcb4f15b7f1e60d,2312
- show-type-0.1.1
- hsblst-0.0.1

- co-log-0.5.0.0
# Required by co-log
- chronos-1.1.5
- co-log-core-0.3.2.0
- typerep-map-0.5.0.0
# Required by chronos
- bytebuild-0.3.11.0
- byteslice-0.2.7.0
- bytesmith-0.3.9.0
# Required by byte*
- run-st-0.1.1.0
- zigzag-0.0.1.0
- contiguous-0.6.2.0

# Packages by Adjoint (somewhat unmaintained, hence they require constraints on their deps)
- galois-field-1.0.2
- elliptic-curve-0.3.0
- pairing-1.1.0
# Required by galois-field.
- protolude-0.2.4
- poly-0.4.0.0
# Required by pairing.
- groups-0.4.1.0
# For keyed BLAKE2b and NaCl secret box
- crypto-sodium-0.0.5.0
# Dependencies of crypto-sodium
- NaCl-0.0.5.0
- libsodium-1.0.18.2
