# SPDX-FileCopyrightText: 2020 TQ Tezos
# SPDX-License-Identifier: LicenseRef-MIT-TQ

resolver: template/snapshot.yaml

packages:
  - .
  - template
  - ligo/haskell
  - ../morley/code/morley
  - ../morley/code/lorentz
  - ../morley/code/cleveland
  - ../morley/code/morley-client

# See extra-deps in template/snapshot.yaml
