# SPDX-FileCopyrightText: 2021 TQ Tezos
# SPDX-License-Identifier: LicenseRef-MIT-TQ

env:
  TEZOS_CLIENT_UNSAFE_DISABLE_DISCLAIMER: "Y"
  # this key is defined in local-chain bootstrap accounts list in
  # https://github.com/serokell/serokell-profiles/blob/master/profiles/servers/jupiter/default.nix
  TASTY_NETTEST_IMPORT_SECRET_KEY: "unencrypted:edsk3nAQ3uCP7vc2ccLhhWNNncgFfWQ5HgTyPawepQ8DURRRfzVQzB"

steps:
  - label: hlint
    if: &not_scheduled
     build.source != "schedule"
    commands:
    - nix run -f ci.nix pkgs.hlint -c
        ./scripts/lint.sh

  - label: reuse lint
    if: *not_scheduled
    commands:
    - nix run -f ci.nix pkgs.reuse -c
        reuse lint

  - label: check trailing whitespace
    if: *not_scheduled
    commands:
    - .buildkite/check-trailing-whitespace.sh

  - label: xrefcheck
    if: *not_scheduled
    commands:
    - nix run -f ci.nix xrefcheck -c xrefcheck
    retry:
      automatic:
        limit: 1

  - label: check cabal files
    if: *not_scheduled
    commands:
    - nix run -f ci.nix stack2cabal pkgs.diffutils -c ./scripts/ci/validate-cabal-files.sh

  - label: build-ligo
    key: build-ligo
    if: *not_scheduled
    commands:
    - nix-build ci.nix -A build-ligo -o ./ligo-out/
    - nix run -f ci.nix morley -c morley optimize --contract ./ligo-out/baseDAO.tz --output baseDAO.tz
    artifact_paths:
      - baseDAO.tz

  - label: build-haskell
    key: build-haskell
    if: *not_scheduled
    commands:
    - nix-build ci.nix -A all-components

  - label: bats
    if: *not_scheduled
    depends_on: build-haskell
    commands:
    - nix run -f ci.nix
          tezos-client
          pkgs.bats
          packages.baseDAO.exes.baseDAO
          packages.baseDAO-ligo-meta.exes.baseDAO-ligo-meta
        -c bats ./scripts/test.bats

  - label: lorentz-test
    if: *not_scheduled
    depends_on: build-haskell
    commands:
      - nix-build ci.nix -A packages.baseDAO.tests.baseDAO-test
      - ./result/bin/baseDAO-test --nettest-no-run-network
  # NOTE (#169): the lorentz version is deprecated, so we only run its tests in
  # an emulated environment to save time.

  - label: ligo-test
    key: ligo-test
    if: *not_scheduled
    depends_on:
      - build-ligo
      - build-haskell
    commands:
    - nix-build ci.nix -A packages.baseDAO-ligo-meta.tests.baseDAO-test
    - ./result/bin/baseDAO-test --nettest-no-run-network

  # TODO #124 uncomment:
  # - label: ligo-test-local-chain-008
  #   env:
  #     TASTY_NETTEST_NODE_ENDPOINT: "http://localhost:8733"
  #   if: *not_scheduled
  #   depends_on:
  #     - build-ligo
  #     - build-haskell
  #     - ligo-test
  #     # NOTE ^ this last dependency is not strictly necessary, but it saves us
  #     # from building the tests twice and 'ligo-test' running time is mostly that.
  #   commands: &ligo-nettest
  #   - nix-build ci.nix -A packages.baseDAO-ligo-meta.tests.baseDAO-test
  #   - export TASTY_NETTEST_DATA_DIR="$(mktemp -d --tmpdir="$$PWD")"
  #   - nix run -f ci.nix tezos-client -c
  #     ./result/bin/baseDAO-test --nettest-run-network
  #       --pattern '\$1 == "On network" || \$NF == "On network" || \$0 ~ /.On network./'

  - label: typescript-build
    depends_on:
      - build-ligo
      - build-haskell
    commands:
    - nix-build ci.nix -A build-typescript --arg release false

  - label: weeder
    if: *not_scheduled
    depends_on: build-haskell
    commands:
    - nix-build ci.nix -A weeder-script
      # weeder needs .cabal file:
      # (most of them are committed, but the one in `template` is not)
    - nix run -f ci.nix pkgs.haskellPackages.hpack -c hpack lorentz/template
    - ./result

  - label: haddock
    if: *not_scheduled
    depends_on: build-haskell
    commands:
    - nix-build ci.nix -A haddock --no-out-link

  # TODO #124 uncomment:
  # - label: scheduled edonet ligo test
  #   if: build.source == "schedule"
  #   env:
  #     TASTY_NETTEST_NODE_ENDPOINT: "http://edo.testnet.tezos.serokell.team:8732"
  #   depends_on:
  #     - build-ligo
  #     - build-haskell
  #   commands: *ligo-nettest
  #   retry:
  #     automatic:
  #       limit: 1

# Autodoc
  - label: contract doc development
    key: contract-doc-dev
    if: &development-only
     build.branch != "autodoc/master" && build.branch != "master" && build.source != "schedule"
    depends_on: build-haskell
    commands:
    - nix-build ci.nix -A contracts-doc --arg release false
    - ln -s ./result/*.md .
    artifact_paths:
      - TrivialDAO.md
      - GameDAO.md
      - RegistryDAO.md
      - TreasuryDAO.md

  - label: xrefcheck generated doc
    soft_fail: true
    if: *development-only
    depends_on: contract-doc-dev
    commands:
    - mkdir tmp
    - buildkite-agent artifact download "*.md" tmp/
        --step "contract doc development"
    - nix run -f ci.nix xrefcheck -c xrefcheck
        --mode local-only --root tmp

  - label: create auto prerelease
    if: build.branch == "master" && build.source != "schedule"
    depends_on: build-ligo
    commands:
      - mkdir assets
      - buildkite-agent artifact download baseDAO.tz assets --step "build-ligo"
      - nix run -f ci.nix pkgs.gitAndTools.gh -c gh release delete auto-release --yes || true
      - nix run -f ci.nix pkgs.git -c git fetch && git tag -f auto-release && git push --force --tags
      - nix run -f ci.nix pkgs.gitAndTools.gh -c gh release create --prerelease auto-release --title auto-release --notes ""
      - nix run -f ci.nix pkgs.gitAndTools.gh -c gh release upload auto-release assets/*


notify:
  - email: "tezos-alerts@serokell.io"
    if: build.state == "failed" && build.source == "schedule"
